/* C code for program USBCTR_SNL, generated by snc from ../USBCTR_SNL.st */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 17 "../USBCTR_SNL.st"
#include <stdlib.h>
# line 18 "../USBCTR_SNL.st"
#include <errlog.h>
# line 19 "../USBCTR_SNL.st"
#include <string.h>
# line 36 "../USBCTR_SNL.st"
static const EF_ID ReadArraysMon = 1;
# line 39 "../USBCTR_SNL.st"
static const EF_ID HardwareAcquiringMon = 2;

/* Variable declarations */
struct seqg_vars {
# line 24 "../USBCTR_SNL.st"
	int i;
# line 25 "../USBCTR_SNL.st"
	int n;
# line 26 "../USBCTR_SNL.st"
	int numCounters;
# line 27 "../USBCTR_SNL.st"
	char temp[100];
# line 29 "../USBCTR_SNL.st"
	char *prefix;
# line 30 "../USBCTR_SNL.st"
	char *record;
# line 31 "../USBCTR_SNL.st"
	char *field;
# line 33 "../USBCTR_SNL.st"
	int ReadArray[9];
# line 35 "../USBCTR_SNL.st"
	int ReadArrays;
# line 38 "../USBCTR_SNL.st"
	int HardwareAcquiring;
# line 41 "../USBCTR_SNL.st"
	int MCSAbsTimeWF;
# line 43 "../USBCTR_SNL.st"
	int SNL_Connected;
# line 44 "../USBCTR_SNL.st"
	int AsynDebug;
# line 47 "../USBCTR_SNL.st"
	int Acquiring;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "mca_control" ******/

/* Event function for state "init" in state set "mca_control" */
static seqBool seqg_event_mca_control_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "mca_control" */
static void seqg_action_mca_control_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 52 "../USBCTR_SNL.st"
			seqg_var->prefix = seq_macValueGet(seqg_env, "P");
# line 53 "../USBCTR_SNL.st"
			seqg_var->record = seq_macValueGet(seqg_env, "R");
# line 54 "../USBCTR_SNL.st"
			seqg_var->field = seq_macValueGet(seqg_env, "FIELD");
# line 55 "../USBCTR_SNL.st"
			seqg_var->numCounters = atoi(seq_macValueGet(seqg_env, "NUM_COUNTERS"));
# line 56 "../USBCTR_SNL.st"
			if ((seqg_var->numCounters <= 0) || (seqg_var->numCounters > 9))
			{
# line 57 "../USBCTR_SNL.st"
				printf("NUM_COUNTERS is illegal.\n");
# line 58 "../USBCTR_SNL.st"
				seqg_var->numCounters = 0;
			}
# line 60 "../USBCTR_SNL.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->numCounters; seqg_var->i++)
			{
# line 61 "../USBCTR_SNL.st"
				seqg_var->n = seqg_var->i + 1;
# line 62 "../USBCTR_SNL.st"
				sprintf(seqg_var->temp, "%s%s%d.%s", seqg_var->prefix, seqg_var->record, seqg_var->n, seqg_var->field);
# line 63 "../USBCTR_SNL.st"
				seq_pvAssign(seqg_env, 0/*ReadArray*/ + (CH_ID)(seqg_var->i), seqg_var->temp);
			}
		}
		return;
	}
}

/****** Code for state "waitConnected" in state set "mca_control" ******/

/* Event function for state "waitConnected" in state set "mca_control" */
static seqBool seqg_event_mca_control_0_waitConnected(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 69 "../USBCTR_SNL.st"
	if (seqg_var->numCounters <= 0)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 73 "../USBCTR_SNL.st"
	if (seq_pvAssignCount(seqg_env) == seq_pvConnectCount(seqg_env))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "waitConnected" in state set "mca_control" */
static void seqg_action_mca_control_0_waitConnected(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 70 "../USBCTR_SNL.st"
			printf(">>>>>>>>>>>>>> USBCTR is dead. <<<<<<<<<<<<<<\n");
		}
		return;
	case 1:
		{
# line 74 "../USBCTR_SNL.st"
			printf("USBCTR: All channels connected.\n");
# line 75 "../USBCTR_SNL.st"
			seqg_var->SNL_Connected = 1;
# line 76 "../USBCTR_SNL.st"
			seq_pvPutTmo(seqg_env, 12/*SNL_Connected*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "dead" in state set "mca_control" ******/

/* Event function for state "dead" in state set "mca_control" */
static seqBool seqg_event_mca_control_0_dead(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 81 "../USBCTR_SNL.st"
	if (seq_delay(seqg_env, 3600.0))
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "dead" in state set "mca_control" */
static void seqg_action_mca_control_0_dead(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "monitor_changes" in state set "mca_control" ******/

/* Event function for state "monitor_changes" in state set "mca_control" */
static seqBool seqg_event_mca_control_0_monitor_changes(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 86 "../USBCTR_SNL.st"
	if (seq_pvAssignCount(seqg_env) != seq_pvConnectCount(seqg_env))
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 90 "../USBCTR_SNL.st"
	if (seq_efTestAndClear(seqg_env, ReadArraysMon) && (seqg_var->ReadArrays == 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 1;
		return TRUE;
	}
# line 102 "../USBCTR_SNL.st"
	if (seq_efTestAndClear(seqg_env, HardwareAcquiringMon))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 2;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "monitor_changes" in state set "mca_control" */
static void seqg_action_mca_control_0_monitor_changes(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 87 "../USBCTR_SNL.st"
			printf("USBCTR: Not all channels connected.\n");
		}
		return;
	case 1:
		{
# line 91 "../USBCTR_SNL.st"
			if (seqg_var->AsynDebug)
# line 91 "../USBCTR_SNL.st"
				printf("USBCTR.st: Read array data\n");
# line 92 "../USBCTR_SNL.st"
			for (seqg_var->i = 0; seqg_var->i < seqg_var->numCounters; seqg_var->i++)
			{
# line 93 "../USBCTR_SNL.st"
				seqg_var->ReadArray[seqg_var->i] = 1;
# line 94 "../USBCTR_SNL.st"
				seq_pvPutTmo(seqg_env, 0/*ReadArray*/ + (CH_ID)(seqg_var->i), DEFAULT, DEFAULT_TIMEOUT);
			}
# line 96 "../USBCTR_SNL.st"
			seqg_var->MCSAbsTimeWF = 1;
# line 97 "../USBCTR_SNL.st"
			seq_pvPutTmo(seqg_env, 11/*MCSAbsTimeWF*/, DEFAULT, DEFAULT_TIMEOUT);
# line 98 "../USBCTR_SNL.st"
			seqg_var->ReadArrays = 0;
# line 99 "../USBCTR_SNL.st"
			seq_pvPutTmo(seqg_env, 9/*ReadArrays*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 2:
		{
# line 103 "../USBCTR_SNL.st"
			if (seqg_var->AsynDebug)
# line 103 "../USBCTR_SNL.st"
				printf("USBCTR.st: HardwareAcquiringMon, HardwareAcquiring=%d\n", seqg_var->HardwareAcquiring);
# line 105 "../USBCTR_SNL.st"
			if (!seqg_var->HardwareAcquiring)
			{
# line 107 "../USBCTR_SNL.st"
				for (seqg_var->i = 0; seqg_var->i < seqg_var->numCounters; seqg_var->i++)
				{
# line 108 "../USBCTR_SNL.st"
					seqg_var->ReadArray[seqg_var->i] = 1;
# line 109 "../USBCTR_SNL.st"
					seq_pvPutTmo(seqg_env, 0/*ReadArray*/ + (CH_ID)(seqg_var->i), SYNC, DEFAULT_TIMEOUT);
				}
# line 111 "../USBCTR_SNL.st"
				seqg_var->MCSAbsTimeWF = 1;
# line 112 "../USBCTR_SNL.st"
				seq_pvPutTmo(seqg_env, 11/*MCSAbsTimeWF*/, DEFAULT, DEFAULT_TIMEOUT);
# line 114 "../USBCTR_SNL.st"
				seqg_var->Acquiring = 0;
# line 115 "../USBCTR_SNL.st"
				seq_pvPutTmo(seqg_env, 14/*Acquiring*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"", offsetof(struct seqg_vars, ReadArray[0]), "ReadArray[0]", P_INT, 1, 3, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[1]), "ReadArray[1]", P_INT, 1, 4, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[2]), "ReadArray[2]", P_INT, 1, 5, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[3]), "ReadArray[3]", P_INT, 1, 6, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[4]), "ReadArray[4]", P_INT, 1, 7, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[5]), "ReadArray[5]", P_INT, 1, 8, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[6]), "ReadArray[6]", P_INT, 1, 9, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[7]), "ReadArray[7]", P_INT, 1, 10, 0, 0, 0, 0},
	{"", offsetof(struct seqg_vars, ReadArray[8]), "ReadArray[8]", P_INT, 1, 11, 0, 0, 0, 0},
	{"{P}DoReadAll", offsetof(struct seqg_vars, ReadArrays), "ReadArrays", P_INT, 1, 12, 1, 1, 0, 0},
	{"{P}HardwareAcquiring", offsetof(struct seqg_vars, HardwareAcquiring), "HardwareAcquiring", P_INT, 1, 13, 2, 1, 0, 0},
	{"{P}AbsTimeWF.PROC", offsetof(struct seqg_vars, MCSAbsTimeWF), "MCSAbsTimeWF", P_INT, 1, 14, 0, 0, 0, 0},
	{"{P}SNL_Connected", offsetof(struct seqg_vars, SNL_Connected), "SNL_Connected", P_INT, 1, 15, 0, 0, 0, 0},
	{"{P}Asyn.TB1", offsetof(struct seqg_vars, AsynDebug), "AsynDebug", P_INT, 1, 16, 0, 1, 0, 0},
	{"{P}Acquiring", offsetof(struct seqg_vars, Acquiring), "Acquiring", P_INT, 1, 17, 0, 0, 0, 0},
};

/* Event masks for state set "mca_control" */
static const seqMask seqg_mask_mca_control_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_mca_control_0_waitConnected[] = {
	0x00000000,
};
static const seqMask seqg_mask_mca_control_0_dead[] = {
	0x00000000,
};
static const seqMask seqg_mask_mca_control_0_monitor_changes[] = {
	0x00001006,
};

/* State table for state set "mca_control" */
static seqState seqg_states_mca_control[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_mca_control_0_init,
	/* event function */    seqg_event_mca_control_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mca_control_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "waitConnected",
	/* action function */   seqg_action_mca_control_0_waitConnected,
	/* event function */    seqg_event_mca_control_0_waitConnected,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mca_control_0_waitConnected,
	/* state options */     (0)
	},
	{
	/* state name */        "dead",
	/* action function */   seqg_action_mca_control_0_dead,
	/* event function */    seqg_event_mca_control_0_dead,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mca_control_0_dead,
	/* state options */     (0)
	},
	{
	/* state name */        "monitor_changes",
	/* action function */   seqg_action_mca_control_0_monitor_changes,
	/* event function */    seqg_event_mca_control_0_monitor_changes,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_mca_control_0_monitor_changes,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "mca_control",
	/* states */            seqg_states_mca_control,
	/* number of states */  4
	},
};

/* Program table (global) */
seqProgram USBCTR_SNL = {
	/* magic number */      2002009,
	/* program name */      "USBCTR_SNL",
	/* channels */          seqg_chans,
	/* num. channels */     15,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "P=USBCTR:MCS:, R=mca, NUM_COUNTERS=8,  FIELD=READ",
	/* num. event flags */  2,
	/* encoded options */   (0 | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void USBCTR_SNLRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&USBCTR_SNL);
}
epicsExportRegistrar(USBCTR_SNLRegistrar);
